# Generated by Django 2.1.7 on 2019-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_address', models.CharField(max_length=128)),
                ('customer_link_man', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_tel', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_principal', models.IntegerField()),
                ('customer_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('row_status', models.IntegerField(blank=True, null=True)),
                ('eid', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('enterprise_name', models.CharField(max_length=50)),
                ('enterprise_link_man', models.CharField(blank=True, max_length=20, null=True)),
                ('enterprise_link_tel', models.CharField(blank=True, max_length=128, null=True)),
                ('enterprise_juridical', models.CharField(blank=True, max_length=20, null=True)),
                ('enterprise_logo', models.CharField(blank=True, max_length=128, null=True)),
                ('enterprise_type', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('row_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enterprise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDepartment',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('eid', models.IntegerField()),
            ],
            options={
                'db_table': 'enterprise_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_type', models.IntegerField()),
                ('order_money', models.DecimalField(decimal_places=5, max_digits=10)),
                ('order_review_status', models.IntegerField()),
                ('order_reviewer', models.IntegerField(blank=True, null=True)),
                ('order_review_time', models.DateTimeField(blank=True, null=True)),
                ('order_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('order_status', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('od_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('storage_stock_id', models.IntegerField()),
                ('num', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=5, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderReturned',
            fields=[
                ('order_id', models.CharField(max_length=20)),
                ('or_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('returned_reviewer', models.IntegerField(blank=True, null=True)),
                ('returned_money', models.DecimalField(decimal_places=5, max_digits=10)),
                ('returned_review_status', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('renturned_review_time', models.DateTimeField(blank=True, null=True)),
                ('create_uid', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('returned_status', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'order_returned',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderReturnedDetails',
            fields=[
                ('rd_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('storage_stock_id', models.IntegerField()),
                ('num', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=0, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'order_returned_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('product_class', models.IntegerField()),
                ('product_describe', models.CharField(blank=True, max_length=500, null=True)),
                ('product_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('create_uid', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_uid', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'prodcut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=128)),
                ('class_fid', models.IntegerField()),
                ('class_remakr', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('update_uid', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'product_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('pd_unit', models.IntegerField()),
                ('pd_standard', models.IntegerField()),
                ('pd_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pd_remark', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('update_uid', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStandard',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('standard_name', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'product_standard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=20)),
                ('create_uid', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('unit_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('storage_name', models.CharField(max_length=50)),
                ('storage_address', models.CharField(max_length=128)),
                ('storage_principal', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('eid', models.IntegerField()),
                ('row_status', models.IntegerField()),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_location', models.CharField(max_length=20)),
                ('storage_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('stock_num', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unit_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('eid', models.IntegerField(blank=True, null=True)),
                ('row_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'storage_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=20)),
                ('supplier_address', models.CharField(max_length=128)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_link_man', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_remark', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('row_status', models.IntegerField(blank=True, null=True)),
                ('eid', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录id')),
                ('token', models.CharField(max_length=128, verbose_name='令牌')),
                ('ip', models.CharField(max_length=50, verbose_name='ip')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('remember', models.IntegerField(verbose_name='记住我')),
                ('uid', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户登录历史',
                'verbose_name_plural': '用户登录历史数据',
                'db_table': 'user_login_history',
                'managed': False,
            },
        ),
    ]
